# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee23e84e0f0c176a958fa7e340f42662662a828caab9a28ddb2c65c7987ef73967914d9a84ed8484c93bf67c770446940c560d8e7b106ec45c68a3afdbd23976

test:
  secret_key_base: 71c6cbdc937c9904af95812107a522e56e48b0cc9d9d1adcd903f34b1dec5110b2d8b7d2f57e2d718840c75eb48dbc1716d3efde2bea2232de683a5e3607515b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
